//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kirin_2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#247BC0")]
        public string MainPalette_Blue {
            get {
                return ((string)(this["MainPalette_Blue"]));
            }
            set {
                this["MainPalette_Blue"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#2BC0E1")]
        public string MainPalette_Cyan {
            get {
                return ((string)(this["MainPalette_Cyan"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#E63E39")]
        public string MainPalette_Red {
            get {
                return ((string)(this["MainPalette_Red"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FAED41")]
        public string MainPalette_Yellow {
            get {
                return ((string)(this["MainPalette_Yellow"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#c7cdd6")]
        public string MainPalette_Gray1 {
            get {
                return ((string)(this["MainPalette_Gray1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WhiteSmoke")]
        public string MainPalette_White {
            get {
                return ((string)(this["MainPalette_White"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ControlLight")]
        public global::System.Drawing.Color color1 {
            get {
                return ((global::System.Drawing.Color)(this["color1"]));
            }
            set {
                this["color1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#26247BC0")]
        public string AlternatingBGColor {
            get {
                return ((string)(this["AlternatingBGColor"]));
            }
            set {
                this["AlternatingBGColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#247BC0")]
        public string Datagrid_header {
            get {
                return ((string)(this["Datagrid_header"]));
            }
            set {
                this["Datagrid_header"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#0D247BC0")]
        public string Datagrid_selector {
            get {
                return ((string)(this["Datagrid_selector"]));
            }
            set {
                this["Datagrid_selector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00be00")]
        public string Datagrid_selectedRow {
            get {
                return ((string)(this["Datagrid_selectedRow"]));
            }
            set {
                this["Datagrid_selectedRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#E62581C6")]
        public string Combobox_bg {
            get {
                return ((string)(this["Combobox_bg"]));
            }
            set {
                this["Combobox_bg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#247BC0")]
        public string Border_color {
            get {
                return ((string)(this["Border_color"]));
            }
            set {
                this["Border_color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#A6247BC0")]
        public string Border_color_inner {
            get {
                return ((string)(this["Border_color_inner"]));
            }
            set {
                this["Border_color_inner"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#33247BC0")]
        public string Modal_bg {
            get {
                return ((string)(this["Modal_bg"]));
            }
            set {
                this["Modal_bg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#A6FFFFFF")]
        public string ClassSelector {
            get {
                return ((string)(this["ClassSelector"]));
            }
            set {
                this["ClassSelector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#E62581C6")]
        public string ClassSelectorHeader {
            get {
                return ((string)(this["ClassSelectorHeader"]));
            }
            set {
                this["ClassSelectorHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#65a2d2")]
        public string Datagrid_header_multidayView {
            get {
                return ((string)(this["Datagrid_header_multidayView"]));
            }
            set {
                this["Datagrid_header_multidayView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#80FFFFFF")]
        public string Subsection_BG {
            get {
                return ((string)(this["Subsection_BG"]));
            }
            set {
                this["Subsection_BG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#D6E4ED")]
        public string AttendanceCheckered {
            get {
                return ((string)(this["AttendanceCheckered"]));
            }
            set {
                this["AttendanceCheckered"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#92B7CA")]
        public string AttendanceCheckeredWhite {
            get {
                return ((string)(this["AttendanceCheckeredWhite"]));
            }
            set {
                this["AttendanceCheckeredWhite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#33247BC0")]
        public string BG_staffprofile {
            get {
                return ((string)(this["BG_staffprofile"]));
            }
            set {
                this["BG_staffprofile"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-H0S5QUB\\MSSQLKIRIN;Initial Catalog=KIRIN;User ID=sa;Password=" +
            "1234")]
        public string Setting1 {
            get {
                return ((string)(this["Setting1"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#4f95cc")]
        public string SPanelItemForeground {
            get {
                return ((string)(this["SPanelItemForeground"]));
            }
            set {
                this["SPanelItemForeground"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-H0S5QUB\\MSSQLKIRIN;Initial Catalog=KIRIN;User ID=sa;Password=" +
            "1234")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#65a2d2")]
        public string LearningSkill_AlterColor1 {
            get {
                return ((string)(this["LearningSkill_AlterColor1"]));
            }
            set {
                this["LearningSkill_AlterColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#91bddf")]
        public string LearningSkill_AlterColor2 {
            get {
                return ((string)(this["LearningSkill_AlterColor2"]));
            }
            set {
                this["LearningSkill_AlterColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#D5D8DC")]
        public string Dashboard_Box_Outline {
            get {
                return ((string)(this["Dashboard_Box_Outline"]));
            }
            set {
                this["Dashboard_Box_Outline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#247BC0")]
        public string ProgressBar_color {
            get {
                return ((string)(this["ProgressBar_color"]));
            }
            set {
                this["ProgressBar_color"] = value;
            }
        }
    }
}
