
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Kirin_2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ASSIGNMENT
{

    public int ASSIGNMENT_ID { get; set; }

    public string UNIQUE_ID { get; set; }

    public string REPORTING_TERM { get; set; }

    public string NAME { get; set; }

    public string ABRV { get; set; }

    public string CATEGORY { get; set; }

    public int POINTS_POSSIBLE { get; set; }

    public double WEIGHT { get; set; }

    public System.DateTime DATE_DUE { get; set; }

    public int SUBJECT_ID { get; set; }

    public string SCORE_TYPE { get; set; }

    public int ISLOADED { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

}

}
