
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Kirin_2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ATTENDANCE_CODES
{

    public int ID { get; set; }

    public string CODE { get; set; }

    public string DESCRIPTION { get; set; }

    public string WEIGHT { get; set; }

    public string COLOR { get; set; }

    public string COLOR2 { get; set; }

}

}
