
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Kirin_2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CLASS_ATTENDANCE
{

    public int ID { get; set; }

    public System.DateTime DATE { get; set; }

    public int STUDENT_ID { get; set; }

    public int SUBJECT_ID { get; set; }

    public string COMMENT { get; set; }

    public string ATTENDANCE_CODE { get; set; }

    public string SECRETARY_COMMENT { get; set; }

}

}
