
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Kirin_2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class DAILYBULLETIN
{

    public int ID { get; set; }

    public Nullable<int> SCHOOLID { get; set; }

    public string MESSAGE { get; set; }

    public Nullable<System.DateTime> UPLOADED_DATE { get; set; }

    public string PRIORITY { get; set; }

}

}
