
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Kirin_2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class GRADE_MASTER
{

    public int ID { get; set; }

    public string Letter { get; set; }

    public Nullable<double> Points { get; set; }

    public string Percent { get; set; }

}

}
