
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Kirin_2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class NOTIFICATION
{

    public int ID { get; set; }

    public string SCHOOLID { get; set; }

    public string MESSAGE { get; set; }

    public Nullable<System.DateTime> UPDATED_DATE { get; set; }

    public byte[] ICON { get; set; }

    public string USERID { get; set; }

    public string NOTIFICATION_TYPE { get; set; }

    public string STUDENT { get; set; }

    public string CLASS { get; set; }

    public string DOCUMENT { get; set; }

    public string UPDATEDBY { get; set; }

    public string STUDENTID { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

}

}
