
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Kirin_2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SCHOOL
{

    public int ID { get; set; }

    public string SCHOOL_NAME { get; set; }

    public int SCHOOLBOARD_ID { get; set; }

    public string ADDRESS { get; set; }

    public string DISTRICT { get; set; }

    public string SCHOOL_TYPE { get; set; }

    public string PHONE_NUMBER { get; set; }

    public string EMAIL { get; set; }

    public string LATITUDE { get; set; }

    public string LONGITUDE { get; set; }

    public string SCHOOL_ID { get; set; }

}

}
