
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Kirin_2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SCHOOLBOARD_ADMINS
{

    public int ID { get; set; }

    public string FIRST_NAME { get; set; }

    public string LAST_NAME { get; set; }

    public string EMAIL { get; set; }

    public string PHONE_NUMBER { get; set; }

    public Nullable<int> ROLEID { get; set; }

    public Nullable<int> SCOOLBOARD_ID { get; set; }

    public Nullable<int> SCHOOL_ID { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

}

}
