
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Kirin_2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SEMESTER
{

    public int ID { get; set; }

    public string SEMESTER1 { get; set; }

    public string ABBREVIATION { get; set; }

    public string YEAR { get; set; }

    public string QUARTER { get; set; }

    public string QUARTERHALF { get; set; }

    public Nullable<System.DateTime> STARTDATE { get; set; }

    public Nullable<System.DateTime> ENDDATE { get; set; }

}

}
