
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Kirin_2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class STAFF_DIRECTORY
{

    public int ID { get; set; }

    public string FIRST_NAME { get; set; }

    public string LAST_NAME { get; set; }

    public Nullable<System.DateTime> BIRTHDATE { get; set; }

    public string ADDRESS { get; set; }

    public string BIRTH_ORIGIN { get; set; }

    public string CITIZENSHIP { get; set; }

    public string ETHNICITY_DIVERSITY { get; set; }

    public Nullable<int> YEARS_OF_EXPERIENCE { get; set; }

    public Nullable<int> SCORE_HAPPINESS { get; set; }

    public Nullable<double> SALARY { get; set; }

    public string SPECIAL_NEEDS_TEACHER { get; set; }

    public string TEACHER_QUALIFICATION { get; set; }

    public string EMAIL { get; set; }

    public string EMPLOYEE_ID { get; set; }

    public string GENDER { get; set; }

    public Nullable<int> ROLEID { get; set; }

    public string ROOM_NUMBER { get; set; }

    public Nullable<int> DEPARTMENTID { get; set; }

    public Nullable<int> SCHOOL_ID { get; set; }

    public string STATUS { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public string SUPERVISOR { get; set; }

}

}
