
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Kirin_2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class STUDENT_AVG_GRADE
{

    public int ID { get; set; }

    public string STUDENTID { get; set; }

    public string SUBJECTID { get; set; }

    public string GRADE1 { get; set; }

    public string GRADE2 { get; set; }

    public string GRADE3 { get; set; }

    public string GRADE4 { get; set; }

    public string GRADE5 { get; set; }

    public string GRADE6 { get; set; }

    public string GRADE7 { get; set; }

    public string GRADE8 { get; set; }

    public string GRADE9 { get; set; }

    public string GRADE10 { get; set; }

    public string GRADE11 { get; set; }

    public string GRADE12 { get; set; }

}

}
