
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Kirin_2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class STUDENT
{

    public int ID { get; set; }

    public string LAST_NAME { get; set; }

    public string FIRST_NAME { get; set; }

    public System.DateTime BIRTHDATE { get; set; }

    public string DIVERSITY { get; set; }

    public string ORIGIN_OF_BIRTH { get; set; }

    public string CITIZENSHIP { get; set; }

    public string ADDRESS { get; set; }

    public string GENDER { get; set; }

    public string ETHNICITY { get; set; }

    public string HOMEROOM { get; set; }

    public string EMAIL { get; set; }

    public string STUDENT_ID { get; set; }

    public Nullable<int> SCHOOL_ID { get; set; }

    public string LATITUDE { get; set; }

    public string LONGITUDE { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<int> ParentCount { get; set; }

    public Nullable<bool> IsTransferred { get; set; }

    public Nullable<int> SiblingCount { get; set; }

    public string HouseholdIncome { get; set; }

    public string Transportation { get; set; }

    public string TransportationAbvr { get; set; }

    public string Parantal_Involvement { get; set; }

    public string Distance { get; set; }

    public string Distance1 { get; set; }

}

}
