
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Kirin_2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class STUDENT_EXTRA_CO
{

    public int ID { get; set; }

    public int STUDENT_ID { get; set; }

    public string EXTRA_CO { get; set; }

    public Nullable<int> CLUB_ID { get; set; }

    public string ABBREVIATION { get; set; }

}

}
