
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Kirin_2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class STUDENT_SCORE
{

    public int STUDENT_SCORE_ID { get; set; }

    public int STUDENT_ID { get; set; }

    public double SCORE_ON_TYPE_OF_EXAM { get; set; }

    public double ENGAGEMENT_SCORE { get; set; }

    public int ASSIGNMENT_ID { get; set; }

    public string POINTS { get; set; }

}

}
