
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Kirin_2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class STUDENT_PHONE_NO
{

    public int ID { get; set; }

    public int STUDENT_ID { get; set; }

    public string PRIMARY_CONTACT { get; set; }

    public string PHONE_NUMBER { get; set; }

    public string RELATION { get; set; }

    public string PRIMARY_EMAIL { get; set; }

}

}
