
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Kirin_2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class STUDENT_TRANSFERRED
{

    public int ID { get; set; }

    public Nullable<int> STUDENT_ID { get; set; }

    public Nullable<int> TRANSFER_TYPE { get; set; }

    public string TRANSFERRED_FROM { get; set; }

    public Nullable<System.DateTime> TRANSFERRED_DATE { get; set; }

}

}
