
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Kirin_2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TEACHER
{

    public int ID { get; set; }

    public string FIRST_NAME { get; set; }

    public string LAST_NAME { get; set; }

    public System.DateTime BIRTHDATE { get; set; }

    public string ADDRESS { get; set; }

    public string BIRTH_ORIGIN { get; set; }

    public string CITIZENSHIP { get; set; }

    public string ETHNICITY_DIVERSITY { get; set; }

    public string LANGUAGES { get; set; }

    public int YEARS_OF_EXPERIENCE { get; set; }

    public string DISCIPLINARY_ACTIONS { get; set; }

    public string COCURRICULAR { get; set; }

    public int SCORE_HAPPINESS { get; set; }

    public double SALARY { get; set; }

    public string TEACHING_STATUS { get; set; }

    public string SPECIAL_NEEDS_TEACHER { get; set; }

    public string DISABILITY { get; set; }

    public string TEACHER_QUALIFICATION { get; set; }

    public string EMAIL { get; set; }

}

}
