
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Kirin_2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TRANSFER_TYPE
{

    public int ID { get; set; }

    public string TRANSFER_TYPE1 { get; set; }

    public string DESCRIPTION { get; set; }

    public string COLOR { get; set; }

}

}
